import React, { createContext, useState, useContext, useEffect } from "react";

const LanguageContext = createContext();

const translations = {
  en: {
    title: "ShramiKare",
    tagline: "Care for the hands that build",
    login: "Login",
    register: "Register",
    doctorDetails: "Doctor Details",
    aadhaarViewer: "Aadhaar Viewer",
    digitalId: "Digital ID",
    dashboard: "Dashboard",
    scanQr: "Scan QR",
    logout: "Logout",
    welcomeBack: "Welcome Back",
    aadhaarNumber: "Aadhaar Number",
    enterAadhaar: "Enter your Aadhaar number",
    sendOtp: "Send OTP",
    sendingOtp: "Sending OTP...",
    enterOtp: "Enter 6-digit OTP",
    verifyOtp: "Verify OTP",
    verifyingOtp: "Verifying...",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    getStarted: "Get Started",
    keyFeatures: "Key Features",
    featuresDesc: "Comprehensive digital migrant healthcare management tools designed for simplicity and effectiveness.",
    secureAuth: "Secure Authentication",
    secureAuthDesc: "OTP-based login for workers and coordinators.",
    facilityFinder: "Facility Finder",
    facilityFinderDesc: "Lookup and contact verified healthcare facilities nearest to worker districts.",
    outbreakAlerts: "Outbreak Detection & Alerts",
    outbreakAlertsDesc: "AI-powered outbreak prediction and timely health SMS reminders.",
    digitalHealthId: "Digital Health ID",
    digitalHealthIdDesc: "Secure identification and record management for every worker.",
    empoweringTitle: "Empowering Migrant Workers with Digital Healthcare",
    empoweringPoint1: "AI-driven digital health alerts, reminders & outbreak notifications.",
    empoweringPoint2: "Easy access to trusted facilities and providers.",
    empoweringPoint3: "Comprehensive health record management.",
    empoweringPoint4: "OTP-based verification and government compliance.",
    healthCareEveryWorker: "Health & Care for Every Worker",
    joinThousands: "Join thousands of workers registering for secure, accessible healthcare management.",
    // Registration
    migrantRegistration: "Migrant Worker Registration",
    fullName: "Full Name",
    enterFullName: "Enter full name",
    age: "Age",
    enterAge: "Enter age",
    gender: "Gender",
    selectGender: "Select gender",
    male: "Male",
    female: "Female",
    other: "Other",
    bloodGroup: "Blood Group",
    selectBloodGroup: "Select blood group",
    languagePref: "Language Preference",
    selectLanguage: "Select language",
    phoneNumber: "Phone Number",
    enterPhoneNumber: "Enter 10-digit mobile number",
    addressInKerala: "Address in Kerala",
    enterAddress: "Enter accommodation or workplace address",
    originState: "Origin State",
    enterOriginState: "e.g., Bihar, West Bengal, Assam",
    originDistrict: "Origin District",
    enterOriginDistrict: "e.g., Patna, Murshidabad",
    destinationDistrict: "Destination District (Kerala)",
    selectDistrict: "Select Kerala district",
    healthRecords: "Health Records",
    vaccinationStatus: "Vaccination Status",
    dose1: "Dose 1 Taken",
    dose2: "Dose 2 Taken",
    specialNotes: "Special Notes / Chronic Illnesses",
    enterSpecialNotes: "e.g., Diabetes, Asthma, None",
    lastVisitReason: "Last Medical Visit Reason",
    enterLastVisitReason: "e.g., Fever, Routine checkup, Injury",
    lastVisitDate: "Last Visit Date",
    visitLocation: "Medical Facility Visited",
    enterVisitLocation: "e.g., General Hospital Ernakulam",
    currentSymptoms: "Current Symptoms",
    fever: "Fever",
    cough: "Cough",
    bodyAches: "Body Aches",
    diarrhea: "Diarrhea",
    skinRash: "Skin Rash",
    breathingDifficulty: "Difficulty Breathing",
    employmentHistory: "Employment History",
    companyName: "Company / Employer Name",
    enterCompanyName: "Enter employer name",
    workingFrom: "Working From (Date)",
    workingTo: "Working To (Date)",
    currentlyWorking: "Currently working here",
    profilePhoto: "Profile Photo",
    aadhaarPhoto: "Aadhaar Card Photo",
    registering: "Registering worker...",
    registerBtn: "Register Worker",
    scanAadhaarBtn: "Scan Aadhaar Card",
    // Digital ID
    digitalHealthIdCard: "Digital Health ID Card",
    officialHealthId: "Your official digital health identification",
    stateOfKerala: "State of Kerala",
    govtOfIndia: "Govt. of India",
    aadhaarVerified: "Aadhaar Verified",
    healthEmploymentDetails: "Health & Employment Details",
    lastVisit: "Last Visit",
    nextFollowUp: "Next Follow Up Date",
    outbreakFlag: "Outbreak Area Warning",
    healthStatus: "Health Status",
    active: "Active",
    identityStatus: "Identity Status",
    verified: "Verified",
    downloadPdf: "Download PDF",
    shareId: "Share ID",
    importantInfo: "Important Information",
    infoPoint1: "This digital ID is valid for all healthcare services in Kerala.",
    infoPoint2: "Keep this ID handy during medical visits and health checkups.",
    infoPoint3: "QR code enables quick verification by healthcare providers.",
    infoPoint4: "Report any discrepancies immediately to local authorities.",
    // Doctor Details / Facilities
    facilitySearch: "Healthcare Facility Registry",
    selectDistrictToSearch: "Select a district to view registered facilities",
    searchButton: "Search Facilities",
    registeredFacilities: "Registered Facilities in",
    noFacilitiesFound: "No facilities found for this district.",
    phone: "Phone",
    services: "Services",
    workingHours: "Working Hours",
    remarks: "Remarks",
  },
  hi: {
    title: "श्रमिकाकेयर",
    tagline: "निर्माण करने वाले हाथों की देखभाल",
    login: "लॉगिन",
    register: "पंजीकरण",
    doctorDetails: "डॉक्टर विवरण",
    aadhaarViewer: "आधार व्यूअर",
    digitalId: "डिजिटल आईडी",
    dashboard: "डैशबोर्ड",
    scanQr: "क्यूआर स्कैन करें",
    logout: "लॉगआउट",
    welcomeBack: "आपका स्वागत है",
    aadhaarNumber: "आधार संख्या",
    enterAadhaar: "अपनी आधार संख्या दर्ज करें",
    sendOtp: "ओटीपी भेजें",
    sendingOtp: "ओटीपी भेजा जा रहा है...",
    enterOtp: "6-अंकीय ओटीपी दर्ज करें",
    verifyOtp: "ओटीपी सत्यापित करें",
    verifyingOtp: "सत्यापित किया जा रहा है...",
    dontHaveAccount: "खाता नहीं है?",
    alreadyHaveAccount: "पहले से ही एक खाता है?",
    getStarted: "शुरू करें",
    keyFeatures: "मुख्य विशेषताएं",
    featuresDesc: "सरलता और प्रभावशीलता के लिए डिज़ाइन किए गए व्यापक डिजिटल प्रवासी स्वास्थ्य सेवा प्रबंधन उपकरण।",
    secureAuth: "सुरक्षित प्रमाणीकरण",
    secureAuthDesc: "श्रमिकों और समन्वयकों के लिए ओटीपी-आधारित लॉगिन।",
    facilityFinder: "सुविधा खोजक",
    facilityFinderDesc: "श्रमिक जिलों के निकटतम सत्यापित स्वास्थ्य सुविधाओं की खोज करें और उनसे संपर्क करें।",
    outbreakAlerts: "प्रकोप का पता लगाना और अलर्ट",
    outbreakAlertsDesc: "एआई-संचालित प्रकोप की भविष्यवाणी और समय पर स्वास्थ्य एसएमएस अनुस्मारक।",
    digitalHealthId: "डिजिटल स्वास्थ्य आईडी",
    digitalHealthIdDesc: "प्रत्येक श्रमिक के लिए सुरक्षित पहचान और रिकॉर्ड प्रबंधन।",
    empoweringTitle: "डिजिटल स्वास्थ्य सेवा के साथ प्रवासी श्रमिकों का सशक्तिकरण",
    empoweringPoint1: "एआई-संचालित डिजिटल स्वास्थ्य अलर्ट, अनुस्मारक और प्रकोप सूचनाएं।",
    empoweringPoint2: "विश्वसनीय सुविधाओं और प्रदाताओं तक आसान पहुंच।",
    empoweringPoint3: "व्यापक स्वास्थ्य रिकॉर्ड प्रबंधन।",
    empoweringPoint4: "ओटीपी-आधारित सत्यापन और सरकारी अनुपालन।",
    healthCareEveryWorker: "हर श्रमिक के लिए स्वास्थ्य और देखभाल",
    joinThousands: "सुरक्षित, सुलभ स्वास्थ्य सेवा प्रबंधन के लिए पंजीकरण कराने वाले हजारों श्रमिकों में शामिल हों।",
    // Registration
    migrantRegistration: "प्रवासी श्रमिक पंजीकरण",
    fullName: "पूरा नाम",
    enterFullName: "पूरा नाम दर्ज करें",
    age: "उम्र",
    enterAge: "उम्र दर्ज करें",
    gender: "लिंग",
    selectGender: "लिंग चुनें",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    bloodGroup: "रक्त समूह",
    selectBloodGroup: "रक्त समूह चुनें",
    languagePref: "भाषा वरीयता",
    selectLanguage: "भाषा चुनें",
    phoneNumber: "फ़ोन नंबर",
    enterPhoneNumber: "10-अंकीय मोबाइल नंबर दर्ज करें",
    addressInKerala: "केरल में पता",
    enterAddress: "आवास या कार्यस्थल का पता दर्ज करें",
    originState: "मूल राज्य",
    enterOriginState: "जैसे, बिहार, पश्चिम बंगाल, असम",
    originDistrict: "मूल जिला",
    enterOriginDistrict: "जैसे, पटना, मुर्शिदाबाद",
    destinationDistrict: "गंतव्य जिला (केरल)",
    selectDistrict: "केरल जिला चुनें",
    healthRecords: "स्वास्थ्य रिकॉर्ड",
    vaccinationStatus: "टीकाकरण की स्थिति",
    dose1: "खुराक 1 ली गई",
    dose2: "खुराक 2 ली गई",
    specialNotes: "विशेष नोट / पुरानी बीमारियां",
    enterSpecialNotes: "जैसे, मधुमेह, अस्थमा, कोई नहीं",
    lastVisitReason: "अंतिम चिकित्सा यात्रा का कारण",
    enterLastVisitReason: "जैसे, बुखार, नियमित जांच, चोट",
    lastVisitDate: "अंतिम यात्रा की तारीख",
    visitLocation: "चिकित्सा सुविधा का दौरा किया",
    enterVisitLocation: "जैसे, जनरल अस्पताल एर्नाकुलम",
    currentSymptoms: "वर्तमान लक्षण",
    fever: "बुखार",
    cough: "खांसी",
    bodyAches: "शरीर में दर्द",
    diarrhea: "दस्त",
    skinRash: "त्वचा पर लाल चकत्ते",
    breathingDifficulty: "सांस लेने में कठिनाई",
    employmentHistory: "रोजगार का इतिहास",
    companyName: "कंपनी / नियोक्ता का नाम",
    enterCompanyName: "नियोक्ता का नाम दर्ज करें",
    workingFrom: "काम करने की शुरुआत (तारीख)",
    workingTo: "काम करने की समाप्ति (तारीख)",
    currentlyWorking: "वर्तमान में यहाँ काम कर रहे हैं",
    profilePhoto: "प्रोफ़ाइल फोटो",
    aadhaarPhoto: "आधार कार्ड फोटो",
    registering: "श्रमिक का पंजीकरण किया जा रहा है...",
    registerBtn: "श्रमिक का पंजीकरण करें",
    scanAadhaarBtn: "आधार कार्ड स्कैन करें",
    // Digital ID
    digitalHealthIdCard: "डिजिटल स्वास्थ्य आईडी कार्ड",
    officialHealthId: "आपकी आधिकारिक डिजिटल स्वास्थ्य पहचान",
    stateOfKerala: "केरल राज्य",
    govtOfIndia: "भारत सरकार",
    aadhaarVerified: "आधार सत्यापित",
    healthEmploymentDetails: "स्वास्थ्य और रोजगार विवरण",
    lastVisit: "अंतिम यात्रा",
    nextFollowUp: "अगली अनुवर्ती तारीख",
    outbreakFlag: "प्रकोप क्षेत्र की चेतावनी",
    healthStatus: "स्वास्थ्य स्थिति",
    active: "सक्रिय",
    identityStatus: "पहचान की स्थिति",
    verified: "सत्यापित",
    downloadPdf: "पीडीएफ डाउनलोड करें",
    shareId: "आईडी साझा करें",
    importantInfo: "महत्वपूर्ण जानकारी",
    infoPoint1: "यह डिजिटल आईडी केरल में सभी स्वास्थ्य सेवाओं के लिए मान्य है।",
    infoPoint2: "चिकित्सा यात्राओं और स्वास्थ्य जांच के दौरान इस आईडी को संभाल कर रखें।",
    infoPoint3: "क्यूआर कोड स्वास्थ्य सेवा प्रदाताओं द्वारा त्वरित सत्यापन सक्षम बनाता है।",
    infoPoint4: "किसी भी विसंगति की सूचना तुरंत स्थानीय अधिकारियों को दें।",
    // Doctor Details / Facilities
    facilitySearch: "स्वास्थ्य सुविधा रजिस्ट्री",
    selectDistrictToSearch: "पंजीकृत सुविधाओं को देखने के लिए एक जिला चुनें",
    searchButton: "सुविधाएं खोजें",
    registeredFacilities: "पंजीकृत सुविधाएं में",
    noFacilitiesFound: "इस जिले के लिए कोई सुविधा नहीं मिली।",
    phone: "फ़ोन",
    services: "सेवाएं",
    workingHours: "कार्य घंटे",
    remarks: "टिप्पणियां",
  },
  ml: {
    title: "ശ്രാമികെയർ",
    tagline: "പണിയെടുക്കുന്ന കൈകൾക്കായി കരുതൽ",
    login: "ലോഗിൻ",
    register: "രജിസ്റ്റർ",
    doctorDetails: "ഡോക്ടർ വിവരങ്ങൾ",
    aadhaarViewer: "ആധാർ വ്യൂവർ",
    digitalId: "ഡിജിറ്റൽ ഐഡി",
    dashboard: "ഡാഷ്‌ബോർഡ്",
    scanQr: "ക്യുആർ സ്കാൻ ചെയ്യുക",
    logout: "ലോഗ് ഔട്ട്",
    welcomeBack: "സ്വാഗതം",
    aadhaarNumber: "ആധാർ നമ്പർ",
    enterAadhaar: "ആധാർ നമ്പർ നൽകുക",
    sendOtp: "ഒടിപി അയക്കുക",
    sendingOtp: "ഒടിപി അയക്കുന്നു...",
    enterOtp: "6 അക്ക ഒടിപി നൽകുക",
    verifyOtp: "ഒടിപി വെരിഫൈ ചെയ്യുക",
    verifyingOtp: "പരിശോധിക്കുന്നു...",
    dontHaveAccount: "അക്കൗണ്ട് ഇല്ലേ?",
    alreadyHaveAccount: "ഇതിനകം ഒരു അക്കൗണ്ട് ഉണ്ടോ?",
    getStarted: "ആരംഭിക്കുക",
    keyFeatures: "പ്രധാന സവിശേഷതകൾ",
    featuresDesc: "അതിഥി തൊഴിലാളികളുടെ ആരോഗ്യ പരിപാലനം ലളിതമാക്കാൻ രൂപകൽപ്പന ചെയ്ത സമഗ്ര ഡിജിറ്റൽ സംവിധാനം.",
    secureAuth: "സുരക്ഷിത ലോഗിൻ",
    secureAuthDesc: "തൊഴിലാളികൾക്കും കോർഡിനേറ്റർമാർക്കും ഒടിപി അടിസ്ഥാനമാക്കിയുള്ള ലോഗിൻ.",
    facilityFinder: "ആശുപത്രി കണ്ടെത്തൽ",
    facilityFinderDesc: "തൊഴിലാളികൾ താമസിക്കുന്ന ജില്ലയ്ക്ക് തൊട്ടടുത്തുള്ള അംഗീകൃത ആശുപത്രികൾ കണ്ടെത്തുക.",
    outbreakAlerts: "രോഗവ്യാപന മുന്നറിയിപ്പുകൾ",
    outbreakAlertsDesc: "എഐ സാങ്കേതികവിദ്യ വഴി രോഗവ്യാപനം മുൻകൂട്ടി കണ്ടെത്തലും എസ്എംഎസ് വഴി വിവരമറിയിക്കലും.",
    digitalHealthId: "ഡിജിറ്റൽ ഹെൽത്ത് ഐഡി",
    digitalHealthIdDesc: "ഓരോ തൊഴിലാളിക്കും സുരക്ഷിതമായ തിരിച്ചറിയൽ കാർഡും ആരോഗ്യ വിവരങ്ങളും.",
    empoweringTitle: "ഡിജിറ്റൽ ഹെൽത്ത് കെയറിലൂടെ അതിഥി തൊഴിലാളികളുടെ ശാക്തീകരണം",
    empoweringPoint1: "എഐ അടിസ്ഥാനമാക്കിയുള്ള ഹെൽത്ത് അലേർട്ടുകളും എസ്എംഎസ് ഓർമ്മപ്പെടുത്തലുകളും.",
    empoweringPoint2: "വിശ്വാസയോഗ്യമായ ആശുപത്രികളിലേക്ക് എളുപ്പത്തിലുള്ള പ്രവേശനം.",
    empoweringPoint3: "സമഗ്ര ആരോഗ്യ വിവര ശേഖരണം.",
    empoweringPoint4: "ഒടിപി വെരിഫിക്കേഷനും സർക്കാർ മാനദണ്ഡങ്ങൾ പാലിക്കലും.",
    healthCareEveryWorker: "എല്ലാ തൊഴിലാളികൾക്കും മികച്ച ആരോഗ്യ പരിപാലനം",
    joinThousands: "സുരക്ഷിതമായ ആരോഗ്യ പരിപാലനത്തിനായി ആയിരക്കണക്കിന് തൊഴിലാളികളോടൊപ്പം പങ്കുചേരൂ.",
    // Registration
    migrantRegistration: "അതിഥി തൊഴിലാളി രജിസ്ട്രേഷൻ",
    fullName: "മുഴുവൻ പേര്",
    enterFullName: "മുഴുവൻ പേര് നൽകുക",
    age: "പ്രായം",
    enterAge: "പ്രായം നൽകുക",
    gender: "ലിംഗഭേദം",
    selectGender: "തിരഞ്ഞെടുക്കുക",
    male: "പുരുഷൻ",
    female: "സ്ത്രീ",
    other: "മറ്റുള്ളവ",
    bloodGroup: "രക്തഗ്രൂപ്പ്",
    selectBloodGroup: "രക്തഗ്രൂപ്പ് തിരഞ്ഞെടുക്കുക",
    languagePref: "ഭാഷാ മുൻഗണന",
    selectLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    phoneNumber: "ഫോൺ നമ്പർ",
    enterPhoneNumber: "10 അക്ക മൊബൈൽ നമ്പർ നൽകുക",
    addressInKerala: "കേരളത്തിലെ വിലാസം",
    enterAddress: "താമസസ്ഥലത്തെ വിലാസം അല്ലെങ്കിൽ ജോലിസ്ഥലം നൽകുക",
    originState: "സ്വന്തം സംസ്ഥാനം",
    enterOriginState: "ഉദാഹരണത്തിന്: ബിഹാർ, പശ്ചിമ ബംഗാൾ, അസം",
    originDistrict: "സ്വന്തം ജില്ല",
    enterOriginDistrict: "ഉദാഹരണത്തിന്: പട്ന, മുർഷിദാബാദ്",
    destinationDistrict: "കേരളത്തിൽ ജോലി ചെയ്യുന്ന ജില്ല",
    selectDistrict: "ജില്ല തിരഞ്ഞെടുക്കുക",
    healthRecords: "ആരോഗ്യ വിവരങ്ങൾ",
    vaccinationStatus: "വാക്സിനേഷൻ വിവരങ്ങൾ",
    dose1: "ഒന്നാം ഡോസ് എടുത്തു",
    dose2: "രണ്ടാം ഡോസ് എടുത്തു",
    specialNotes: "പ്രത്യേക കുറിപ്പുകൾ / മറ്റ് അസുഖങ്ങൾ",
    enterSpecialNotes: "ഉദാഹരണത്തിന്: പ്രമേഹം, ആസ്ത്മ, ഒന്നുമില്ല",
    lastVisitReason: "അവസാനം ചികിത്സ തേടിയതിന്റെ കാരണം",
    enterLastVisitReason: "ഉദാഹരണത്തിന്: പനി, പതിവ് പരിശോധന, പരിക്ക്",
    lastVisitDate: "അവസാനം ആശുപത്രിയിൽ പോയ തീയതി",
    visitLocation: "ചികിത്സ തേടിയ ആശുപത്രി",
    enterVisitLocation: "ഉദാഹരണത്തിന്: ജനറൽ ഹോസ്പിറ്റൽ എറണാകുളം",
    currentSymptoms: "നിലവിലുള്ള ലക്ഷണങ്ങൾ",
    fever: "പനി",
    cough: "ചുമ",
    bodyAches: "ശരീരവേദന",
    diarrhea: "വയറിളക്കം",
    skinRash: "ചൊറിഞ്ഞ് തിണർക്കൽ",
    breathingDifficulty: "ശ്വാസതടസ്സം",
    employmentHistory: "തൊഴിൽ വിവരങ്ങൾ",
    companyName: "കമ്പനി / കരാറുകാരന്റെ പേര്",
    enterCompanyName: "കമ്പനിയുടെ പേര് നൽകുക",
    workingFrom: "ജോലി ആരംഭിച്ച തീയതി",
    workingTo: "ജോലി അവസാനിച്ച തീയതി",
    currentlyWorking: "ഇപ്പോഴും ഇവിടെ ജോലി ചെയ്യുന്നു",
    profilePhoto: "പ്രൊഫൈൽ ഫോട്ടോ",
    aadhaarPhoto: "ആധാർ കാർഡ് ഫോട്ടോ",
    registering: "രജിസ്റ്റർ ചെയ്യുന്നു...",
    registerBtn: "തൊഴിലാളിയെ രജിസ്റ്റർ ചെയ്യുക",
    scanAadhaarBtn: "ആധാർ കാർഡ് സ്കാൻ ചെയ്യുക",
    // Digital ID
    digitalHealthIdCard: "ഡിജിറ്റൽ ഹെൽത്ത് ഐഡി കാർഡ്",
    officialHealthId: "നിങ്ങളുടെ ഔദ്യോഗിക ആരോഗ്യ കാർഡ്",
    stateOfKerala: "കേരള സർക്കാർ",
    govtOfIndia: "ഭാരത സർക്കാർ",
    aadhaarVerified: "ആധാർ പരിശോധിച്ചുറപ്പിച്ചു",
    healthEmploymentDetails: "ആരോഗ്യ തീയതികളും തൊഴിൽ വിവരങ്ങളും",
    lastVisit: "അവസാന സന്ദർശനം",
    nextFollowUp: "അടുത്ത സന്ദർശന തീയതി",
    outbreakFlag: "രോഗവ്യാപന മേഖല മുന്നറിയിപ്പ്",
    healthStatus: "ആരോഗ്യ നില",
    active: "ആക്ടീവ്",
    identityStatus: "തിരിച്ചറിയൽ നില",
    verified: "വെരിഫൈഡ്",
    downloadPdf: "പിഡിഎഫ് ഡൗൺലോഡ് ചെയ്യുക",
    shareId: "കാർഡ് പങ്കുവെക്കുക",
    importantInfo: "പ്രധാന വിവരങ്ങൾ",
    infoPoint1: "ഈ ഡിജിറ്റൽ കാർഡ് കേരളത്തിലെ എല്ലാ ആരോഗ്യ സേവനങ്ങൾക്കും ഉപയോഗിക്കാം.",
    infoPoint2: "ആശുപത്രി സന്ദർശന വേളകളിൽ ഈ കാർഡ് കയ്യിൽ കരുതുക.",
    infoPoint3: "ക്യുആർ കോഡ് ഉപയോഗിച്ച് ആരോഗ്യ കേന്ദ്രങ്ങളിൽ വിവരങ്ങൾ വേഗത്തിൽ പരിശോധിക്കാം.",
    infoPoint4: "വിവരങ്ങളിൽ തെറ്റുകൾ ഉണ്ടെങ്കിൽ ബന്ധപ്പെട്ട അധികാരികളെ അറിയിക്കുക.",
    // Doctor Details / Facilities
    facilitySearch: "ആരോഗ്യ കേന്ദ്രങ്ങളുടെ വിവരങ്ങൾ",
    selectDistrictToSearch: "ആശുപത്രികൾ കാണുന്നതിനായി ഒരു ജില്ല തിരഞ്ഞെടുക്കുക",
    searchButton: "ആശുപത്രികൾ തിരയുക",
    registeredFacilities: "രജിസ്റ്റർ ചെയ്ത ആശുപത്രികൾ - ജില്ല:",
    noFacilitiesFound: "ഈ ജില്ലയിൽ ആശുപത്രികൾ ഒന്നും കണ്ടെത്തിയില്ല.",
    phone: "ഫോൺ",
    services: "സേവനങ്ങൾ",
    workingHours: "പ്രവർത്തന സമയം",
    remarks: "കൂടുതൽ വിവരങ്ങൾ",
  },
  ta: {
    title: "ஷ்ராமிகேர்",
    tagline: "கட்டும் கரங்களுக்கு பாதுகாப்பு",
    login: "உள்நுழைவு",
    register: "பதிவு செய்க",
    doctorDetails: "மருத்துவ விபரங்கள்",
    aadhaarViewer: "ஆதார் வியூவர்",
    digitalId: "டிஜிட்டல் ஐடி",
    dashboard: "டாஷ்போர்டு",
    scanQr: "கியூஆர் ஸ்கேன் செய்க",
    logout: "வெளியேறு",
    welcomeBack: "வரவேற்கிறோம்",
    aadhaarNumber: "ஆதார் எண்",
    enterAadhaar: "உங்கள் ஆதார் எண்ணை உள்ளிடவும்",
    sendOtp: "ஓடிபி அனுப்புக",
    sendingOtp: "ஓடிபி அனுப்பப்படுகிறது...",
    enterOtp: "6 இலக்க ஓடிபி உள்ளிடவும்",
    verifyOtp: "ஓடிபி சரிபார்க்கவும்",
    verifyingOtp: "சரிபார்க்கப்படுகிறது...",
    dontHaveAccount: "கணக்கு இல்லையா?",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    getStarted: "தொடங்குங்கள்",
    keyFeatures: "முக்கிய அம்சங்கள்",
    featuresDesc: "புலம்பெயர் தொழிலாளர்களின் சுகாதார மேலாண்மையை எளிதாக்க வடிவமைக்கப்பட்ட விரிவான டிஜிட்டல் தளம்.",
    secureAuth: "பாதுகாப்பான உள்நுழைவு",
    secureAuthDesc: "தொழிலாளர்கள் மற்றும் ஒருங்கிணைப்பாளர்களுக்கான ஓடிபி அடிப்படையிலான உள்நுழைவு.",
    facilityFinder: "மருத்துவமனை தேடல்",
    facilityFinderDesc: "தொழிலாளர்கள் வசிக்கும் மாவட்டத்திற்கு அருகிலுள்ள மருத்துவமனைகளை தேடிக் கண்டறியவும்.",
    outbreakAlerts: "தொற்று நோய் எச்சரிக்கைகள்",
    outbreakAlertsDesc: "எஐ தொழில்நுட்பம் மூலம் தொற்று நோய்களை முன்கூட்டியே கண்டறிதல் மற்றும் எஸ்எம்எஸ் எச்சரிக்கைகள்.",
    digitalHealthId: "டிஜிட்டல் சுகாதார அட்டை",
    digitalHealthIdDesc: "ஒவ்வொரு தொழிலாளிக்கும் பாதுகாப்பான அடையாள அட்டை மற்றும் மருத்துவப் பதிவுகள்.",
    empoweringTitle: "டிஜிட்டல் சுகாதார சேவை மூலம் புலம்பெயர் தொழிலாளர்களின் மேம்பாடு",
    empoweringPoint1: "எஐ அடிப்படையிலான சுகாதார எச்சரிக்கைகள் மற்றும் எஸ்எம்எஸ் நினைவூட்டல்கள்.",
    empoweringPoint2: "நம்பகமான மருத்துவமனைகளுக்கு எளிதான அணுகல்.",
    empoweringPoint3: "விரிவான மருத்துவ பதிவு மேலாண்மை.",
    empoweringPoint4: "ஓடிபி சரிபார்ப்பு மற்றும் அரசு இணக்கங்கள்.",
    healthCareEveryWorker: "ஒவ்வொரு தொழிலாளிக்கும் ஆரோக்கியம் மற்றும் பாதுகாப்பு",
    joinThousands: "பாதுகாப்பான மருத்துவ சேவையைப் பெற ஆயிரக்கணக்கான தொழிலாளர்களுடன் இணையுங்கள்.",
    // Registration
    migrantRegistration: "புலம்பெயர் தொழிலாளர் பதிவு",
    fullName: "முழு பெயர்",
    enterFullName: "முழு பெயரை உள்ளிடவும்",
    age: "வயது",
    enterAge: "வயதை உள்ளிடவும்",
    gender: "பாலினம்",
    selectGender: "பாலினத்தை தேர்வு செய்யவும்",
    male: "ஆண்",
    female: "பெண்",
    other: "மற்றவை",
    bloodGroup: "இரத்த வகை",
    selectBloodGroup: "இரத்த வகையை தேர்வு செய்யவும்",
    languagePref: "மொழி விருப்பம்",
    selectLanguage: "மொழியை தேர்வு செய்யவும்",
    phoneNumber: "தொலைபேசி எண்",
    enterPhoneNumber: "10 இலக்க மொபைல் எண்ணை உள்ளிடவும்",
    addressInKerala: "கேரளாவில் முகவரி",
    enterAddress: "தங்குமிடம் அல்லது பணியிட முகவரியை உள்ளிடவும்",
    originState: "சொந்த மாநிலம்",
    enterOriginState: "எ.கா: பீகார், மேற்கு வங்கம், அசாம்",
    originDistrict: "சொந்த மாவட்டம்",
    enterOriginDistrict: "எ.கா: பாட்னா, முர்ஷிதாபாத்",
    destinationDistrict: "பணிபுரியும் மாவட்டம் (கேரளா)",
    selectDistrict: "கேரள மாவட்டத்தைத் தேர்வு செய்யவும்",
    healthRecords: "சுகாதாரப் பதிவுகள்",
    vaccinationStatus: "தடுப்பூசி விபரம்",
    dose1: "முதல் டோஸ் எடுக்கப்பட்டது",
    dose2: "இரண்டாம் டோஸ் எடுக்கப்பட்டது",
    specialNotes: "குறிப்பு / நீண்ட நாள் நோய்கள்",
    enterSpecialNotes: "எ.கா: சர்க்கரை நோய், ஆஸ்துமா, ஏதுமில்லை",
    lastVisitReason: "கடைசி மருத்துவ வருகைக்கான காரணம்",
    enterLastVisitReason: "எ.கா: காய்ச்சல், வழக்கமான பரிசோதனை, காயம்",
    lastVisitDate: "கடைசி மருத்துவ வருகை தேதி",
    visitLocation: "சிகிச்சை பெற்ற மருத்துவமனை",
    enterVisitLocation: "எ.கா: எர்ணாகுளம் பொது மருத்துவமனை",
    currentSymptoms: "தற்போதைய அறிகுறிகள்",
    fever: "காய்ச்சல்",
    cough: "இருமல்",
    bodyAches: "உடல் வலி",
    diarrhea: "வயிற்றுப்போக்கு",
    skinRash: "தோல் அரிப்பு / தடிப்பு",
    breathingDifficulty: "மூச்சுத் திணறல்",
    employmentHistory: "வேலைவாய்ப்பு விபரம்",
    companyName: "நிறுவனம் / முதலாளியின் பெயர்",
    enterCompanyName: "முதலாளி பெயரை உள்ளிடவும்",
    workingFrom: "பணியில் சேர்ந்த தேதி",
    workingTo: "பணி முடிந்த தேதி",
    currentlyWorking: "தற்போது இங்கு வேலை செய்கிறேன்",
    profilePhoto: "சுயவிவரப் புகைப்படம்",
    aadhaarPhoto: "ஆதார் கார்டு புகைப்படம்",
    registering: "தொழிலாளி பதிவு செய்யப்படுகிறது...",
    registerBtn: "தொழிலாளியைப் பதிவு செய்க",
    scanAadhaarBtn: "ஆதார் கார்டு ஸ்கேன் செய்க",
    // Digital ID
    digitalHealthIdCard: "டிஜிட்டல் சுகாதார அடையாள அட்டை",
    officialHealthId: "உங்களது அதிகாரப்பூர்வ டிஜிட்டல் சுகாதார அட்டை",
    stateOfKerala: "கேரள அரசு",
    govtOfIndia: "இந்திய அரசு",
    aadhaarVerified: "ஆதார் சரிபார்க்கப்பட்டது",
    healthEmploymentDetails: "சுகாதார மற்றும் வேலை விபரங்கள்",
    lastVisit: "கடைசி வருகை",
    nextFollowUp: "அடுத்த வருகை தேதி",
    outbreakFlag: "தொற்று நோய் பகுதி எச்சரிக்கை",
    healthStatus: "சுகாதார நிலை",
    active: "செயலில்",
    identityStatus: "அடையாள நிலை",
    verified: "சரிபார்க்கப்பட்டது",
    downloadPdf: "பிடிஎஃப் பதிவிறக்கு",
    shareId: "அட்டையைப் பகிர்",
    importantInfo: "முக்கிய தகவல்கள்",
    infoPoint1: "இந்த டிஜிட்டல் அட்டை கேரளாவில் உள்ள அனைத்து மருத்துவ சேவைகளுக்கும் செல்லுபடியாகும்.",
    infoPoint2: "மருத்துவமனைக்குச் செல்லும்போது இந்த அட்டையைக் கையில் வைத்திருக்கவும்.",
    infoPoint3: "கியூஆர் கோடு மூலம் மருத்துவமனைகளில் தகவல்களை விரைவாக சரிபார்க்கலாம்.",
    infoPoint4: "தகவல்களில் ஏதேனும் தவறு இருந்தால் அதிகாரிகளிடம் தெரிவிக்கவும்.",
    // Doctor Details / Facilities
    facilitySearch: "மருத்துவமனை விபரப் பதிவேடு",
    selectDistrictToSearch: "மருத்துவமனைகளைப் பார்க்க ஒரு மாவட்டத்தைத் தேர்வு செய்யவும்",
    searchButton: "மருத்துவமனைகளைத் தேடு",
    registeredFacilities: "பதிவு செய்யப்பட்ட மருத்துவமனைகள் - மாவட்டம்:",
    noFacilitiesFound: "இந்த மாவட்டத்தில் மருத்துவமனைகள் ஏதும் கண்டறியப்படவில்லை.",
    phone: "தொலைபேசி",
    services: "சேவைகள்",
    workingHours: "பணி நேரம்",
    remarks: "குறிப்புகள்",
  },
  bn: {
    title: "শ্রমিককেয়ার",
    tagline: "নির্মাণকারী হাতগুলোর যত্ন",
    login: "লগইন",
    register: "নিবন্ধন",
    doctorDetails: "ডাক্তারের বিবরণ",
    aadhaarViewer: "আধার ভিউয়ার",
    digitalId: "ডিজিটাল আইডি",
    dashboard: "ড্যাশবোর্ড",
    scanQr: "কিউআর স্ক্যান করুন",
    logout: "লগআউট",
    welcomeBack: "আপনাকে স্বাগত",
    aadhaarNumber: "আধার নম্বর",
    enterAadhaar: "আপনার আধার নম্বর লিখুন",
    sendOtp: "ওটিপি পাঠান",
    sendingOtp: "ওটিপি পাঠানো হচ্ছে...",
    enterOtp: "৬ ডিজিটের ওটিপি লিখুন",
    verifyOtp: "ওটিপি যাচাই করুন",
    verifyingOtp: "যাচাই করা হচ্ছে...",
    dontHaveAccount: "অ্যাকাউন্ট নেই?",
    alreadyHaveAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    getStarted: "শুরু করুন",
    keyFeatures: "মূল বৈশিষ্ট্যসমূহ",
    featuresDesc: "সহজ এবং কার্যকর করার জন্য ডিজাইন করা ব্যাপক ডিজিটাল পরিযায়ী স্বাস্থ্যসেবা ব্যবস্থাপনা সরঞ্জাম।",
    secureAuth: "সুরক্ষিত প্রমাণীকরণ",
    secureAuthDesc: "শ্রমিক এবং সমন্বয়কারীদের জন্য ওটিপি-ভিত্তিক লগইন।",
    facilityFinder: "হাসপাতাল অনুসন্ধান",
    facilityFinderDesc: "শ্রমিক জেলাগুলির নিকটবর্তী যাচাইকৃত স্বাস্থ্য কেন্দ্রগুলি অনুসন্ধান এবং যোগাযোগ করুন।",
    outbreakAlerts: "প্রকোপ সনাক্তকরণ ও সতর্কতা",
    outbreakAlertsDesc: "এআই-চালিত প্রাদুর্ভাবের পূর্বাভাস এবং সময়মতো স্বাস্থ্য এসএমএস অনুস্মারক।",
    digitalHealthId: "ডিজিটাল স্বাস্থ্য আইডি",
    digitalHealthIdDesc: "প্রতিটি শ্রমিকের জন্য সুরক্ষিত পরিচয় এবং রেকর্ড ব্যবস্থাপনা।",
    empoweringTitle: "ডিজিটাল স্বাস্থ্যসেবা সহ পরিযায়ী শ্রমিকদের ক্ষমতায়ন",
    empoweringPoint1: "এআই-চালিত ডিজিটাল স্বাস্থ্য সতর্কতা, অনুস্মারক এবং প্রাদুর্ভাবের বিজ্ঞপ্তি।",
    empoweringPoint2: "নির্ভরযোগ্য সুবিধা এবং ডাক্তারদের সহজ অ্যাক্সেস।",
    empoweringPoint3: "ব্যাপক স্বাস্থ্য রেকর্ড ব্যবস্থাপনা।",
    empoweringPoint4: "ওটিপি-ভিত্তিক যাচাইকরণ এবং সরকারি সম্মতি।",
    healthCareEveryWorker: "প্রতিটি শ্রমিকের জন্য স্বাস্থ্য ও যত্ন",
    joinThousands: "সুরক্ষিত, অ্যাক্সেসযোগ্য স্বাস্থ্যসেবা ব্যবস্থাপনার জন্য নিবন্ধনকারী হাজার হাজার শ্রমিকের সাথে যোগ দিন।",
    // Registration
    migrantRegistration: "পরিযায়ী শ্রমিক নিবন্ধন",
    fullName: "পুরো নাম",
    enterFullName: "পুরো নাম লিখুন",
    age: "বয়স",
    enterAge: "বয়স লিখুন",
    gender: "লিঙ্গ",
    selectGender: "লিঙ্গ নির্বাচন করুন",
    male: "পুরুষ",
    female: "মহিলা",
    other: "অন্যান্য",
    bloodGroup: "রক্তের গ্রুপ",
    selectBloodGroup: "রক্তের গ্রুপ নির্বাচন করুন",
    languagePref: "ভাষার পছন্দ",
    selectLanguage: "ভাষা নির্বাচন করুন",
    phoneNumber: "ফোন নম্বর",
    enterPhoneNumber: "১০ ডিজিটের মোবাইল নম্বর লিখুন",
    addressInKerala: "কেরালার ঠিকানা",
    enterAddress: "বাসস্থান বা কর্মক্ষেত্রের ঠিকানা লিখুন",
    originState: "মূল রাজ্য",
    enterOriginState: "যেমন, বিহার, পশ্চিমবঙ্গ, আসাম",
    originDistrict: "মূল জেলা",
    enterOriginDistrict: "যেমন, পাটনা, মুর্শিদাবাদ",
    destinationDistrict: "গন্তব্য জেলা (কেরালা)",
    selectDistrict: "কেরালার জেলা নির্বাচন করুন",
    healthRecords: "স্বাস্থ্য রেকর্ড",
    vaccinationStatus: "টিকাকরণ স্থিতি",
    dose1: "প্রথম ডোজ নেওয়া হয়েছে",
    dose2: "দ্বিতীয় ডোজ নেওয়া হয়েছে",
    specialNotes: "বিশেষ নোট / দীর্ঘস্থায়ী রোগ",
    enterSpecialNotes: "যেমন, ডায়াবেটিস, হাঁপানি, কোনোটিই নয়",
    lastVisitReason: "শেষ চিকিৎসার কারণ",
    enterLastVisitReason: "যেমন, জ্বর, রুটিন চেকআপ, আঘাত",
    lastVisitDate: "শেষ পরিদর্শনের তারিখ",
    visitLocation: "চিকিৎসা কেন্দ্র পরিদর্শন করেছেন",
    enterVisitLocation: "যেমন, জেনারেল হাসপাতাল এরনাকুলাম",
    currentSymptoms: "বর্তমান লক্ষণসমূহ",
    fever: "জ্বর",
    cough: "কাশি",
    bodyAches: "গায়ে ব্যথা",
    diarrhea: "ডায়রিয়া",
    skinRash: "চামড়ায় ফুসকুড়ি",
    breathingDifficulty: "শ্বাসকষ্ট",
    employmentHistory: "কর্মসংস্থানের ইতিহাস",
    companyName: "কোম্পানি / নিয়োগকর্তার নাম",
    enterCompanyName: "নিয়োগকর্তার নাম লিখুন",
    workingFrom: "কাজের শুরু (তারিখ)",
    workingTo: "কাজের সমাপ্তি (তারিখ)",
    currentlyWorking: "বর্তমানে এখানে কাজ করছেন",
    profilePhoto: "প্রোফাইল ছবি",
    aadhaarPhoto: "আধার কার্ডের ছবি",
    registering: "শ্রমিক নিবন্ধন করা হচ্ছে...",
    registerBtn: "শ্রমিক নিবন্ধন করুন",
    scanAadhaarBtn: "আধার কার্ড স্ক্যান করুন",
    // Digital ID
    digitalHealthIdCard: "ডিজিটাল স্বাস্থ্য আইডি কার্ড",
    officialHealthId: "আপনার অফিসিয়াল ডিজিটাল স্বাস্থ্য পরিচয়পত্র",
    stateOfKerala: "কেরালা রাজ্য",
    govtOfIndia: "ভারত সরকার",
    aadhaarVerified: "আধার যাচাইকৃত",
    healthEmploymentDetails: "স্বাস্থ্য এবং কর্মসংস্থান বিবরণ",
    lastVisit: "শেষ পরিদর্শন",
    nextFollowUp: "পরবর্তী ফলো-আপ তারিখ",
    outbreakFlag: "প্রকোপ এলাকার সতর্কতা",
    healthStatus: "স্বাস্থ্য স্থিতি",
    active: "সক্রিয়",
    identityStatus: "পরিচয়ের স্থিতি",
    verified: "যাচাইকৃত",
    downloadPdf: "পিডিএফ ডাউনলোড করুন",
    shareId: "আইডি শেয়ার করুন",
    importantInfo: "গুরুত্বপূর্ণ তথ্য",
    infoPoint1: "এই ডিজিটাল আইডি কেরালায় সমস্ত স্বাস্থ্য পরিষেবার জন্য বৈধ।",
    infoPoint2: "চিকিৎসা ও স্বাস্থ্য পরীক্ষার সময় এই আইডিটি সাথে রাখুন।",
    infoPoint3: "কিউআর কোড স্বাস্থ্যসেবা প্রদানকারীদের দ্বারা দ্রুত যাচাইকরণ সক্ষম করে।",
    infoPoint4: "যেকোনো অসঙ্গতির কথা অবিলম্বে স্থানীয় কর্তৃপক্ষকে জানান।",
    // Doctor Details / Facilities
    facilitySearch: "স্বাস্থ্য কেন্দ্র রেজিস্ট্রি",
    selectDistrictToSearch: "নিবন্ধিত হাসপাতাল দেখতে একটি জেলা নির্বাচন করুন",
    searchButton: "হাসপাতাল খুঁজুন",
    registeredFacilities: "নিবন্ধিত হাসপাতাল সমূহ - জেলা:",
    noFacilitiesFound: "এই জেলায় কোনো হাসপাতাল পাওয়া যায়নি।",
    phone: "ফোন",
    services: "সেবাসমূহ",
    workingHours: "কাজের সময়",
    remarks: "মন্তব্য",
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("shramikare_lang") || "en";
  });

  useEffect(() => {
    localStorage.setItem("shramikare_lang", language);
  }, [language]);

  const t = (key) => {
    const langData = translations[language] || translations.en;
    return langData[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
